version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./:/app/
    restart: unless-stopped
  posthunter:
    build: .
    env_file: .env
    volumes:
      - ./:/app/
    command: ["sh", "-c", "python posthunter_runner.py"]
    restart: unless-stopped
  